name: Flutter - Android Build Dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v7

#      - name: Setup JDK
#        uses: actions/setup-java@v6
#        with:
#          java-version: '21'
#          distribution: temurin
#      - run: java --version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.44.8

      - name: Clean dependencies
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: integration test
        run: flutter test integration_test/navigation_test.dart -d android

      - name: Build APK
#        run: flutter build apk --release --build-name=1.0.0 --build-number=1
        run: flutter build apk --debug --build-name=1.0.0 --build-number=1

