name: Flutter - Android Build Dev

on:
  push:
    branches:
      - master1
  pull_request:
    branches:
      - master1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v7

      - name: Setup JDK
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: temurin
      - run: java --version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.44.8

      - name: Clean dependencies
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

#      - name: integration test
#        run: flutter test integration_test/navigation_test.dart -d PNZHUCPF4P65OZBA
      - name: Widget test
        run: flutter test test/unit_and_widget_test/animation_screen_test.dart

      - name: Build APK
#        run: flutter build apk --release --build-name=1.0.0 --build-number=1
        run: flutter build apk --debug --build-name=1.0.0 --build-number=1

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk